name: flutter_uploader_example
version: 3.0.0-beta.3
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.3
  path_provider: ^2.0.8
  image_picker: ^1.1.1
  shared_preferences: ^2.0.5
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_uploader:
    path: ../

flutter:
  uses-material-design: true
